name: Domain Check

on:
    push:
        branches: ['main']
    pull_request:
        branches: ['main']

jobs:
    DomainCheck:
        runs-on: ubuntu-latest
        steps:
            # Checkout the code
            - name: Checkout
              uses: actions/checkout@v4
            - name: Run Domain Check
              run: ./ops/domainCheck.sh
              shell: bash
